import { z } from 'zod';

export const FacilityStatusSchema = z.object({
    id: z.number(),
    total_patients_count: z.number(),
    man_patients_count: z.number(),
    woman_patients_count: z.number(),
    user_capacity: z.number(),
    doctor_count: z.number(),
    manager_count: z.number(),
    hb_doctor_count: z.number(),
    dent_doctor_count: z.number(),
    medc_doctor_count: z.number(),
    hb_resdnt_count: z.number(),
    hb_sp_count: z.number(),
    hb_gn_count: z.number(),
    hb_intn_count: z.number(),
    dent_gn_count: z.number(),
    dent_resdnt_count: z.number(),
    dent_sp_count: z.number(),
    medc_resdnt_count: z.number(),
    medc_gn_count: z.number(),
    medc_intn_count: z.number(),
    medc_sp_count: z.number(),
    facility_id: z.number(),
    created_at: z.string().nullable(),
    updated_at: z.string().nullable(),
});

export const FacilitySchema = z.object({
    id: z.number(),
    kind: z.string(),
    name: z.string(),
    address: z.string(),
    url: z.string().nullable(),
    telno: z.string(),
    description: z.string().nullable(),
    approval_status: z.string().nullable(),
    sido_name: z.string(),
    sggu_name: z.string(),
    dong_name: z.string(),
    postno: z.string(),
    established_date: z.number(),
    longitude: z.number(),
    latitude: z.number(),
    care_code: z.string(),
    facility_number: z.string().nullable(),
    average_rating: z.number(),
    review_count: z.number(),
    created_at: z.string().nullable(),
    updated_at: z.string().nullable(),
    distance: z.number(),
    facility_status: FacilityStatusSchema,
    advertisements: z.array(z.unknown()),
});

export type FacilityData = z.infer<typeof FacilitySchema>;
