import { z } from 'zod';

export const FacilityStatusSchema = z.object({
  id: z.number().nullable(),
  total_patients_count: z.number().nullable(),
  man_patients_count: z.number(),
  woman_patients_count: z.number().nullable(),
  user_capacity: z.number().nullable(),
  doctor_count: z.number().nullable(),
  manager_count: z.number().nullable(),
  hb_doctor_count: z.number().nullable(),
  dent_doctor_count: z.number().nullable(),
  medc_doctor_count: z.number().nullable(),
  hb_resdnt_count: z.number().nullable(),
  hb_sp_count: z.number().nullable(),
  hb_gn_count: z.number().nullable(),
  hb_intn_count: z.number().nullable(),
  dent_gn_count: z.number().nullable(),
  dent_resdnt_count: z.number().nullable(),
  dent_sp_count: z.number().nullable(),
  medc_resdnt_count: z.number().nullable(),
  medc_gn_count: z.number().nullable(),
  medc_intn_count: z.number().nullable(),
  medc_sp_count: z.number().nullable(),
  facility_id: z.number().nullable(),
  created_at: z.string().nullable(),
  updated_at: z.string().nullable(),
});

export const FacilityDataSchema = z.object({
  id: z.number(),
  kind: z.string(),
  name: z.string(),
  average_rating: z.number(),
  review_count: z.number(),
  advertisements: z.array(z.unknown()),
  longitude: z.number().nullable(),
  latitude: z.number().nullable(),
  address: z.string().nullable(),
  url: z.string().nullable(),
  telno: z.string().nullable(),
  description: z.string().nullable(),
  approval_status: z.string().nullable(),
  sido_name: z.string().nullable(),
  sggu_name: z.string().nullable(),
  dong_name: z.string().nullable(),
  postno: z.string().nullable(),
  established_date: z.number().nullable(),
  care_code: z.string().nullable(),
  facility_number: z.string().nullable(),
  created_at: z.string().nullable(),
  updated_at: z.string().nullable(),
  facility_status: FacilityStatusSchema,
});

export type FacilityData_t = z.infer<typeof FacilityDataSchema>;
