const getFacilities = () => {
    const res = {
        Message: 'Facility select successfully.',
        ResultCode: 'ERR_OK',
        Size: 20,
        Response: [
            {
                id: 3902,
                kind: '요양병원',
                name: '(의)밀성학원의료재단 성모요양병원',
                address: '경상남도 김해시 김해대로 2479-1, (삼정동)',
                url: '',
                telno: '055-320-2080',
                description: null,
                approval_status: null,
                sido_name: '경남',
                sggu_name: '김해시',
                dong_name: '삼정동',
                postno: '50934',
                established_date: 20100727,
                longitude: '128.8980324',
                latitude: '35.2281381',
                care_code:
                    'JDQ4MTYyMiM4MSMkMSMkNCMkOTkkNTgxMzUxIzIxIyQxIyQ1IyQ4OSQzNjE4MzIjNjEjJDEjJDAjJDgz',
                facility_number: null,
                created_at: '2025-09-16T04:13:40.581Z',
                updated_at: '2025-09-16T04:13:40.581Z',
                facility_status: {
                    id: 1337,
                    total_patients_count: 0,
                    man_patients_count: 0,
                    woman_patients_count: 0,
                    user_capacity: 0,
                    doctor_count: 5,
                    manager_count: 0,
                    hb_doctor_count: 0,
                    dent_doctor_count: 0,
                    medc_doctor_count: 0,
                    hb_resdnt_count: 0,
                    hb_sp_count: 0,
                    hb_gn_count: 2,
                    hb_intn_count: 0,
                    dent_gn_count: 0,
                    dent_resdnt_count: 0,
                    dent_sp_count: 0,
                    medc_resdnt_count: 0,
                    medc_gn_count: 0,
                    medc_intn_count: 0,
                    medc_sp_count: 3,
                    facility_id: 3902,
                    created_at: null,
                    updated_at: null,
                },
                advertisement: null,
            },
            {
                id: 3903,
                kind: '요양병원',
                name: '(의)수의료재단 서청솔요양병원',
                address: '경상남도 김해시 금관대로1084번길 15, (흥동)',
                url: '',
                telno: '055-310-5500',
                description: null,
                approval_status: null,
                sido_name: '경남',
                sggu_name: '김해시',
                dong_name: '흥동',
                postno: '50963',
                established_date: 20190207,
                longitude: '128.8507902',
                latitude: '35.2240003',
                care_code:
                    'JDQ4MTYyMiM4MSMkMSMkNCMkOTkkNTgxMzUxIzIxIyQxIyQ1IyQ4MiQzNjEyMjIjNTEjJDEjJDIjJDgz',
                facility_number: null,
                created_at: '2025-09-16T04:13:40.593Z',
                updated_at: '2025-09-16T04:13:40.593Z',
                facility_status: {
                    id: 1338,
                    total_patients_count: 0,
                    man_patients_count: 0,
                    woman_patients_count: 0,
                    user_capacity: 0,
                    doctor_count: 7,
                    manager_count: 0,
                    hb_doctor_count: 0,
                    dent_doctor_count: 0,
                    medc_doctor_count: 0,
                    hb_resdnt_count: 0,
                    hb_sp_count: 1,
                    hb_gn_count: 1,
                    hb_intn_count: 0,
                    dent_gn_count: 0,
                    dent_resdnt_count: 0,
                    dent_sp_count: 0,
                    medc_resdnt_count: 0,
                    medc_gn_count: 1,
                    medc_intn_count: 0,
                    medc_sp_count: 4,
                    facility_id: 3903,
                    created_at: null,
                    updated_at: null,
                },
                advertisement: null,
            },
            {
                id: 3904,
                kind: '요양병원',
                name: '(의)영님의료재단 개금중앙요양병원',
                address:
                    '부산광역시 부산진구 개금온정로 5, 지하1,지상3층 (개금동, 성원상떼뷰)',
                url: 'http://www.개금중앙요양병원.kr/',
                telno: '051-582-7001',
                description: null,
                approval_status: null,
                sido_name: '부산',
                sggu_name: '부산진구',
                dong_name: '개금동',
                postno: '47268',
                established_date: 20100816,
                longitude: '129.0247934',
                latitude: '35.1537626',
                care_code:
                    'JDQ4MTAxMiM1MSMkMSMkMCMkOTkkNTgxMzUxIzIxIyQxIyQxIyQ2MiQyNjEyMjIjNDEjJDEjJDgjJDgz',
                facility_number: null,
                created_at: '2025-09-16T04:13:40.606Z',
                updated_at: '2025-09-16T04:13:40.606Z',
                facility_status: {
                    id: 1339,
                    total_patients_count: 0,
                    man_patients_count: 0,
                    woman_patients_count: 0,
                    user_capacity: 0,
                    doctor_count: 6,
                    manager_count: 0,
                    hb_doctor_count: 0,
                    dent_doctor_count: 0,
                    medc_doctor_count: 0,
                    hb_resdnt_count: 0,
                    hb_sp_count: 1,
                    hb_gn_count: 1,
                    hb_intn_count: 0,
                    dent_gn_count: 1,
                    dent_resdnt_count: 0,
                    dent_sp_count: 0,
                    medc_resdnt_count: 0,
                    medc_gn_count: 0,
                    medc_intn_count: 0,
                    medc_sp_count: 3,
                    facility_id: 3904,
                    created_at: null,
                    updated_at: null,
                },
                advertisement: null,
            },
            {
                id: 3905,
                kind: '요양병원',
                name: '(의)피터의료재단새소망요양병원',
                address: '부산광역시 기장군 기장읍 기장해안로 552, (기장읍)',
                url: '',
                telno: '051-722-4848',
                description: null,
                approval_status: null,
                sido_name: '부산',
                sggu_name: '부산기장군',
                dong_name: '기장읍',
                postno: '46079',
                established_date: 20050317,
                longitude: '129.2269050',
                latitude: '35.2228262',
                care_code:
                    'JDQ4MTAxMiM1MSMkMSMkMCMkOTkkNTgxMzUxIzExIyQxIyQzIyQ4MiQyNjE4MzIjNDEjJDEjJDgjJDgz',
                facility_number: null,
                created_at: '2025-09-16T04:13:40.618Z',
                updated_at: '2025-09-16T04:13:40.618Z',
                facility_status: {
                    id: 1340,
                    total_patients_count: 0,
                    man_patients_count: 0,
                    woman_patients_count: 0,
                    user_capacity: 0,
                    doctor_count: 4,
                    manager_count: 0,
                    hb_doctor_count: 0,
                    dent_doctor_count: 0,
                    medc_doctor_count: 0,
                    hb_resdnt_count: 0,
                    hb_sp_count: 0,
                    hb_gn_count: 2,
                    hb_intn_count: 0,
                    dent_gn_count: 0,
                    dent_resdnt_count: 0,
                    dent_sp_count: 0,
                    medc_resdnt_count: 0,
                    medc_gn_count: 0,
                    medc_intn_count: 0,
                    medc_sp_count: 2,
                    facility_id: 3905,
                    created_at: null,
                    updated_at: null,
                },
                advertisement: null,
            },
            {
                id: 3906,
                kind: '요양병원',
                name: '(의)현당의료재단 늘봄요양병원',
                address:
                    '경기도 용인시 수지구 포은대로59번길 17, 광교복합의료센터,지하1층,1층일부,2층~4층,6층 (상현동)',
                url: '',
                telno: '031-659-7800',
                description: null,
                approval_status: null,
                sido_name: '경기',
                sggu_name: '용인수지구',
                dong_name: '상현동',
                postno: '16864',
                established_date: 20180425,
                longitude: '127.0658441',
                latitude: '37.3010717',
                care_code:
                    'JDQ4MTYyMiM1MSMkMSMkMCMkOTkkNTgxMzUxIzQxIyQxIyQ3IyQxMyQzNjE0ODEjODEjJDEjJDIjJDgz',
                facility_number: null,
                created_at: '2025-09-16T04:13:40.628Z',
                updated_at: '2025-09-16T04:13:40.628Z',
                facility_status: {
                    id: 1341,
                    total_patients_count: 0,
                    man_patients_count: 0,
                    woman_patients_count: 0,
                    user_capacity: 0,
                    doctor_count: 6,
                    manager_count: 0,
                    hb_doctor_count: 0,
                    dent_doctor_count: 0,
                    medc_doctor_count: 0,
                    hb_resdnt_count: 0,
                    hb_sp_count: 0,
                    hb_gn_count: 0,
                    hb_intn_count: 0,
                    dent_gn_count: 0,
                    dent_resdnt_count: 0,
                    dent_sp_count: 0,
                    medc_resdnt_count: 0,
                    medc_gn_count: 0,
                    medc_intn_count: 0,
                    medc_sp_count: 6,
                    facility_id: 3906,
                    created_at: null,
                    updated_at: null,
                },
                advertisement: null,
            },
            {
                id: 3907,
                kind: '요양병원',
                name: '(의)환명의료재단 경상남도립김해노인전문병원',
                address: '경상남도 김해시 김해대로 1814-39, (삼계동)',
                url: 'http://gimhaenoin.co.kr/',
                telno: '055-330-2000',
                description: null,
                approval_status: null,
                sido_name: '경남',
                sggu_name: '김해시',
                dong_name: '삼계동',
                postno: '50880',
                established_date: 20050712,
                longitude: '128.8610034',
                latitude: '35.2616213',
                care_code:
                    'JDQ4MTYyMiM4MSMkMSMkNCMkOTkkNTgxMzUxIzExIyQyIyQzIyQwMCQyNjEyMjIjODEjJDEjJDYjJDgz',
                facility_number: null,
                created_at: '2025-09-16T04:13:40.640Z',
                updated_at: '2025-09-16T04:13:40.640Z',
                facility_status: {
                    id: 1342,
                    total_patients_count: 0,
                    man_patients_count: 0,
                    woman_patients_count: 0,
                    user_capacity: 0,
                    doctor_count: 6,
                    manager_count: 0,
                    hb_doctor_count: 0,
                    dent_doctor_count: 0,
                    medc_doctor_count: 0,
                    hb_resdnt_count: 0,
                    hb_sp_count: 0,
                    hb_gn_count: 2,
                    hb_intn_count: 0,
                    dent_gn_count: 0,
                    dent_resdnt_count: 0,
                    dent_sp_count: 0,
                    medc_resdnt_count: 0,
                    medc_gn_count: 0,
                    medc_intn_count: 0,
                    medc_sp_count: 4,
                    facility_id: 3907,
                    created_at: null,
                    updated_at: null,
                },
                advertisement: null,
            },
            {
                id: 3908,
                kind: '요양병원',
                name: '365강서수요양병원',
                address:
                    '서울특별시 강서구 양천로 35, 1~6층 (방화동, 강서성심병원)',
                url: '',
                telno: '02-2663-0075',
                description: null,
                approval_status: null,
                sido_name: '서울',
                sggu_name: '강서구',
                dong_name: '방화동',
                postno: '07516',
                established_date: 20160919,
                longitude: '126.8077064',
                latitude: '37.5729765',
                care_code:
                    'JDQ4MTg4MSM1MSMkMSMkMCMkOTkkNTgxMzUxIzIxIyQyIyQxIyQwMCQ0NjE0ODEjNDEjJDEjJDQjJDgz',
                facility_number: null,
                created_at: '2025-09-16T04:13:40.651Z',
                updated_at: '2025-09-16T04:13:40.651Z',
                facility_status: {
                    id: 1343,
                    total_patients_count: 0,
                    man_patients_count: 0,
                    woman_patients_count: 0,
                    user_capacity: 0,
                    doctor_count: 4,
                    manager_count: 0,
                    hb_doctor_count: 0,
                    dent_doctor_count: 0,
                    medc_doctor_count: 0,
                    hb_resdnt_count: 0,
                    hb_sp_count: 0,
                    hb_gn_count: 1,
                    hb_intn_count: 0,
                    dent_gn_count: 0,
                    dent_resdnt_count: 0,
                    dent_sp_count: 0,
                    medc_resdnt_count: 0,
                    medc_gn_count: 0,
                    medc_intn_count: 0,
                    medc_sp_count: 3,
                    facility_id: 3908,
                    created_at: null,
                    updated_at: null,
                },
                advertisement: null,
            },
            {
                id: 3909,
                kind: '요양병원',
                name: 'BB요양병원',
                address: '울산광역시 북구 염포로 353, (양정동)',
                url: '',
                telno: '052-716-1020',
                description: null,
                approval_status: null,
                sido_name: '울산',
                sggu_name: '울산북구',
                dong_name: '양정동',
                postno: '44257',
                established_date: 20161111,
                longitude: '129.3780269',
                latitude: '35.5593556',
                care_code:
                    'JDQ4MTYyMiM4MSMkMSMkNCMkOTkkNTgxMzUxIzIxIyQyIyQ1IyQwMCQzNjE4MzIjODEjJDEjJDYjJDgz',
                facility_number: null,
                created_at: '2025-09-16T04:13:40.660Z',
                updated_at: '2025-09-16T04:13:40.660Z',
                facility_status: {
                    id: 1344,
                    total_patients_count: 0,
                    man_patients_count: 0,
                    woman_patients_count: 0,
                    user_capacity: 0,
                    doctor_count: 4,
                    manager_count: 0,
                    hb_doctor_count: 0,
                    dent_doctor_count: 0,
                    medc_doctor_count: 0,
                    hb_resdnt_count: 0,
                    hb_sp_count: 0,
                    hb_gn_count: 2,
                    hb_intn_count: 0,
                    dent_gn_count: 0,
                    dent_resdnt_count: 0,
                    dent_sp_count: 0,
                    medc_resdnt_count: 0,
                    medc_gn_count: 0,
                    medc_intn_count: 0,
                    medc_sp_count: 2,
                    facility_id: 3909,
                    created_at: null,
                    updated_at: null,
                },
                advertisement: null,
            },
            {
                id: 3910,
                kind: '요양병원',
                name: 'SKJ상경원요양병원',
                address: '경기도 여주시 강천면 걸촌동길 33-4, (강천면)',
                url: '',
                telno: '1600-5075',
                description: null,
                approval_status: null,
                sido_name: '경기',
                sggu_name: '여주시',
                dong_name: '강천면',
                postno: '12616',
                established_date: 20241127,
                longitude: '127.7021570',
                latitude: '37.2890394',
                care_code:
                    'JDQ4MTYyMiM1MSMkMSMkMCMkOTkkNTgxMzUxIzUxIyQyIyQxIyQwMCQzNjEwMDIjODEjJDEjJDYjJDgz',
                facility_number: null,
                created_at: '2025-09-16T04:13:40.672Z',
                updated_at: '2025-09-16T04:13:40.672Z',
                facility_status: {
                    id: 1345,
                    total_patients_count: 0,
                    man_patients_count: 0,
                    woman_patients_count: 0,
                    user_capacity: 0,
                    doctor_count: 1,
                    manager_count: 0,
                    hb_doctor_count: 0,
                    dent_doctor_count: 0,
                    medc_doctor_count: 0,
                    hb_resdnt_count: 0,
                    hb_sp_count: 0,
                    hb_gn_count: 0,
                    hb_intn_count: 0,
                    dent_gn_count: 0,
                    dent_resdnt_count: 0,
                    dent_sp_count: 0,
                    medc_resdnt_count: 0,
                    medc_gn_count: 0,
                    medc_intn_count: 0,
                    medc_sp_count: 1,
                    facility_id: 3910,
                    created_at: null,
                    updated_at: null,
                },
                advertisement: null,
            },
            {
                id: 3911,
                kind: '요양병원',
                name: '가나안요양병원',
                address: '부산광역시 수영구 수영로 563-1, 지하1~10층 (광안동)',
                url: '',
                telno: '051-752-8000',
                description: null,
                approval_status: null,
                sido_name: '부산',
                sggu_name: '부산수영구',
                dong_name: '광안동',
                postno: '48261',
                established_date: 20190520,
                longitude: '129.1124247',
                latitude: '35.1561769',
                care_code:
                    'JDQ4MTAxMiM1MSMkMSMkMCMkOTkkNTgxMzUxIzIxIyQxIyQ5IyQ3OSQyNjEwMDIjNjEjJDEjJDgjJDgz',
                facility_number: null,
                created_at: '2025-09-16T04:13:46.829Z',
                updated_at: '2025-09-16T04:13:46.829Z',
                facility_status: {
                    id: 1346,
                    total_patients_count: 0,
                    man_patients_count: 0,
                    woman_patients_count: 0,
                    user_capacity: 0,
                    doctor_count: 5,
                    manager_count: 0,
                    hb_doctor_count: 0,
                    dent_doctor_count: 0,
                    medc_doctor_count: 0,
                    hb_resdnt_count: 0,
                    hb_sp_count: 0,
                    hb_gn_count: 2,
                    hb_intn_count: 0,
                    dent_gn_count: 0,
                    dent_resdnt_count: 0,
                    dent_sp_count: 0,
                    medc_resdnt_count: 0,
                    medc_gn_count: 0,
                    medc_intn_count: 0,
                    medc_sp_count: 3,
                    facility_id: 3911,
                    created_at: null,
                    updated_at: null,
                },
                advertisement: null,
            },
            {
                id: 3912,
                kind: '요양병원',
                name: '가야요양병원',
                address:
                    '충청남도 천안시 동남구 영성로 7, (영성동, 가야요양병원)',
                url: '',
                telno: '041-558-1000',
                description: null,
                approval_status: null,
                sido_name: '충남',
                sggu_name: '천안동남구',
                dong_name: '영성동',
                postno: '31130',
                established_date: 20140108,
                longitude: '127.1505959',
                latitude: '36.7989313',
                care_code:
                    'JDQ4MTYyMiM2MSMkMSMkMiMkOTkkNTgxMzUxIzExIyQxIyQ3IyQxMyQzNjEwMDIjODEjJDEjJDYjJDgz',
                facility_number: null,
                created_at: '2025-09-16T04:13:46.839Z',
                updated_at: '2025-09-16T04:13:46.839Z',
                facility_status: {
                    id: 1347,
                    total_patients_count: 0,
                    man_patients_count: 0,
                    woman_patients_count: 0,
                    user_capacity: 0,
                    doctor_count: 5,
                    manager_count: 0,
                    hb_doctor_count: 0,
                    dent_doctor_count: 0,
                    medc_doctor_count: 0,
                    hb_resdnt_count: 0,
                    hb_sp_count: 0,
                    hb_gn_count: 1,
                    hb_intn_count: 0,
                    dent_gn_count: 0,
                    dent_resdnt_count: 0,
                    dent_sp_count: 0,
                    medc_resdnt_count: 0,
                    medc_gn_count: 0,
                    medc_intn_count: 0,
                    medc_sp_count: 4,
                    facility_id: 3912,
                    created_at: null,
                    updated_at: null,
                },
                advertisement: null,
            },
            {
                id: 3913,
                kind: '요양병원',
                name: '가야이요양병원',
                address: '경상북도 성주군 성주읍 주산로 183, (성주읍)',
                url: '',
                telno: '054-933-7002',
                description: null,
                approval_status: null,
                sido_name: '경북',
                sggu_name: '성주군',
                dong_name: '성주읍',
                postno: '40031',
                established_date: 20080212,
                longitude: '128.3040306',
                latitude: '35.9330786',
                care_code:
                    'JDQ4MTYyMiM4MSMkMSMkMCMkOTkkNTgxMzUxIzExIyQxIyQ3IyQ4OSQ0NjE0ODEjNjEjJDEjJDgjJDgz',
                facility_number: null,
                created_at: '2025-09-16T04:13:46.848Z',
                updated_at: '2025-09-16T04:13:46.848Z',
                facility_status: {
                    id: 1348,
                    total_patients_count: 0,
                    man_patients_count: 0,
                    woman_patients_count: 0,
                    user_capacity: 0,
                    doctor_count: 4,
                    manager_count: 0,
                    hb_doctor_count: 0,
                    dent_doctor_count: 0,
                    medc_doctor_count: 0,
                    hb_resdnt_count: 0,
                    hb_sp_count: 0,
                    hb_gn_count: 1,
                    hb_intn_count: 0,
                    dent_gn_count: 0,
                    dent_resdnt_count: 0,
                    dent_sp_count: 0,
                    medc_resdnt_count: 0,
                    medc_gn_count: 0,
                    medc_intn_count: 0,
                    medc_sp_count: 3,
                    facility_id: 3913,
                    created_at: null,
                    updated_at: null,
                },
                advertisement: null,
            },
            {
                id: 3914,
                kind: '요양병원',
                name: '가온요양병원',
                address:
                    '인천광역시 남동구 남동대로 797, 가온 요양병원 (구월동)',
                url: 'www.gaonhospital.co.kr',
                telno: '032-212-2001',
                description: null,
                approval_status: null,
                sido_name: '인천',
                sggu_name: '인천남동구',
                dong_name: '구월동',
                postno: '21555',
                established_date: 20170629,
                longitude: '126.7078003',
                latitude: '37.4535770',
                care_code:
                    'JDQ4MTYyMiM1MSMkMSMkMCMkOTkkNTgxMzUxIzMxIyQxIyQ3IyQ4OSQzNjEyMjIjNDEjJDEjJDQjJDgz',
                facility_number: null,
                created_at: '2025-09-16T04:13:46.858Z',
                updated_at: '2025-09-16T04:13:46.858Z',
                facility_status: {
                    id: 1349,
                    total_patients_count: 0,
                    man_patients_count: 0,
                    woman_patients_count: 0,
                    user_capacity: 0,
                    doctor_count: 7,
                    manager_count: 0,
                    hb_doctor_count: 0,
                    dent_doctor_count: 0,
                    medc_doctor_count: 0,
                    hb_resdnt_count: 0,
                    hb_sp_count: 0,
                    hb_gn_count: 1,
                    hb_intn_count: 0,
                    dent_gn_count: 0,
                    dent_resdnt_count: 0,
                    dent_sp_count: 0,
                    medc_resdnt_count: 0,
                    medc_gn_count: 1,
                    medc_intn_count: 0,
                    medc_sp_count: 5,
                    facility_id: 3914,
                    created_at: null,
                    updated_at: null,
                },
                advertisement: null,
            },
            {
                id: 3915,
                kind: '요양병원',
                name: '가은병원',
                address:
                    '경기도 부천시 소사구 마니로24번길 43-17, (송내동, 가은병원A동)',
                url: 'http://www.gaeunhospital.com/',
                telno: '032-667-0114',
                description: null,
                approval_status: null,
                sido_name: '경기',
                sggu_name: '부천소사구',
                dong_name: '송내동',
                postno: '14746',
                established_date: 20021115,
                longitude: '126.7688451',
                latitude: '37.4774648',
                care_code:
                    'JDQ4MTYyMiM1MSMkMSMkMCMkOTkkNTgxMzUxIzExIyQxIyQzIyQ3MiQzNjEwMDIjNTEjJDEjJDIjJDgz',
                facility_number: null,
                created_at: '2025-09-16T04:13:46.869Z',
                updated_at: '2025-09-16T04:13:46.869Z',
                facility_status: {
                    id: 1350,
                    total_patients_count: 0,
                    man_patients_count: 0,
                    woman_patients_count: 0,
                    user_capacity: 0,
                    doctor_count: 13,
                    manager_count: 0,
                    hb_doctor_count: 0,
                    dent_doctor_count: 0,
                    medc_doctor_count: 0,
                    hb_resdnt_count: 0,
                    hb_sp_count: 0,
                    hb_gn_count: 1,
                    hb_intn_count: 0,
                    dent_gn_count: 0,
                    dent_resdnt_count: 0,
                    dent_sp_count: 0,
                    medc_resdnt_count: 0,
                    medc_gn_count: 1,
                    medc_intn_count: 0,
                    medc_sp_count: 11,
                    facility_id: 3915,
                    created_at: null,
                    updated_at: null,
                },
                advertisement: null,
            },
            {
                id: 3916,
                kind: '요양병원',
                name: '가족사랑 요양병원',
                address: '부산광역시 부산진구 새싹로 286, 4~9층 (초읍동)',
                url: '',
                telno: '051-806-1190',
                description: null,
                approval_status: null,
                sido_name: '부산',
                sggu_name: '부산진구',
                dong_name: '초읍동',
                postno: '47124',
                established_date: 20051212,
                longitude: '129.0473059',
                latitude: '35.1816671',
                care_code:
                    'JDQ4MTAxMiM1MSMkMSMkMCMkOTkkNTgxMzUxIzIxIyQxIyQ1IyQ4OSQzNjEyMjIjODEjJDEjJDIjJDgz',
                facility_number: null,
                created_at: '2025-09-16T04:13:46.880Z',
                updated_at: '2025-09-16T04:13:46.880Z',
                facility_status: {
                    id: 1351,
                    total_patients_count: 0,
                    man_patients_count: 0,
                    woman_patients_count: 0,
                    user_capacity: 0,
                    doctor_count: 6,
                    manager_count: 0,
                    hb_doctor_count: 0,
                    dent_doctor_count: 0,
                    medc_doctor_count: 0,
                    hb_resdnt_count: 0,
                    hb_sp_count: 0,
                    hb_gn_count: 2,
                    hb_intn_count: 0,
                    dent_gn_count: 0,
                    dent_resdnt_count: 0,
                    dent_sp_count: 0,
                    medc_resdnt_count: 0,
                    medc_gn_count: 0,
                    medc_intn_count: 0,
                    medc_sp_count: 4,
                    facility_id: 3916,
                    created_at: null,
                    updated_at: null,
                },
                advertisement: null,
            },
            {
                id: 3917,
                kind: '요양병원',
                name: '가창파티마요양병원',
                address: '대구광역시 달성군 가창면 가창로85길 24-6, (가창면)',
                url: '',
                telno: '053-295-7000',
                description: null,
                approval_status: null,
                sido_name: '대구',
                sggu_name: '대구달성군',
                dong_name: '가창면',
                postno: '42939',
                established_date: 20160428,
                longitude: '128.6497959',
                latitude: '35.7499693',
                care_code:
                    'JDQ4MTYyMiM4MSMkMSMkMCMkOTkkNTgxMzUxIzIxIyQxIyQ1IyQ5OSQyNjEyMjIjNzEjJDEjJDgjJDgz',
                facility_number: null,
                created_at: '2025-09-16T04:13:46.888Z',
                updated_at: '2025-09-16T04:13:46.888Z',
                facility_status: {
                    id: 1352,
                    total_patients_count: 0,
                    man_patients_count: 0,
                    woman_patients_count: 0,
                    user_capacity: 0,
                    doctor_count: 4,
                    manager_count: 0,
                    hb_doctor_count: 0,
                    dent_doctor_count: 0,
                    medc_doctor_count: 0,
                    hb_resdnt_count: 0,
                    hb_sp_count: 0,
                    hb_gn_count: 1,
                    hb_intn_count: 0,
                    dent_gn_count: 0,
                    dent_resdnt_count: 0,
                    dent_sp_count: 0,
                    medc_resdnt_count: 0,
                    medc_gn_count: 0,
                    medc_intn_count: 0,
                    medc_sp_count: 3,
                    facility_id: 3917,
                    created_at: null,
                    updated_at: null,
                },
                advertisement: null,
            },
            {
                id: 3918,
                kind: '요양병원',
                name: '가평산속요양병원',
                address: '경기도 가평군 상면 대보간선로 889, (상면)',
                url: 'www.gpnature.com/',
                telno: '031-584-8900',
                description: null,
                approval_status: null,
                sido_name: '경기',
                sggu_name: '가평군',
                dong_name: '상면',
                postno: '12445',
                established_date: 20121008,
                longitude: '127.4044314',
                latitude: '37.7889464',
                care_code:
                    'JDQ4MTYyMiM1MSMkMSMkMCMkOTkkNTgxMzUxIzMxIyQxIyQzIyQ4OSQyNjE0ODEjNjEjJDEjJDAjJDgz',
                facility_number: null,
                created_at: '2025-09-16T04:13:46.899Z',
                updated_at: '2025-09-16T04:13:46.899Z',
                facility_status: {
                    id: 1353,
                    total_patients_count: 0,
                    man_patients_count: 0,
                    woman_patients_count: 0,
                    user_capacity: 0,
                    doctor_count: 2,
                    manager_count: 0,
                    hb_doctor_count: 0,
                    dent_doctor_count: 0,
                    medc_doctor_count: 0,
                    hb_resdnt_count: 0,
                    hb_sp_count: 0,
                    hb_gn_count: 1,
                    hb_intn_count: 0,
                    dent_gn_count: 0,
                    dent_resdnt_count: 0,
                    dent_sp_count: 0,
                    medc_resdnt_count: 0,
                    medc_gn_count: 0,
                    medc_intn_count: 0,
                    medc_sp_count: 1,
                    facility_id: 3918,
                    created_at: null,
                    updated_at: null,
                },
                advertisement: null,
            },
            {
                id: 3919,
                kind: '요양병원',
                name: '가평푸른숲요양병원',
                address: '경기도 가평군 상면 물골길 262-23, (상면)',
                url: '',
                telno: '1661-9099',
                description: null,
                approval_status: null,
                sido_name: '경기',
                sggu_name: '가평군',
                dong_name: '상면',
                postno: '12440',
                established_date: 20170901,
                longitude: '127.3042465',
                latitude: '37.8409105',
                care_code:
                    'JDQ4MTYyMiM1MSMkMSMkMCMkOTkkNTgxMzUxIzQxIyQxIyQ3IyQ5MiQyNjEyMjIjNzEjJDEjJDgjJDgz',
                facility_number: null,
                created_at: '2025-09-16T04:13:46.911Z',
                updated_at: '2025-09-16T04:13:46.911Z',
                facility_status: {
                    id: 1354,
                    total_patients_count: 0,
                    man_patients_count: 0,
                    woman_patients_count: 0,
                    user_capacity: 0,
                    doctor_count: 4,
                    manager_count: 0,
                    hb_doctor_count: 0,
                    dent_doctor_count: 0,
                    medc_doctor_count: 0,
                    hb_resdnt_count: 0,
                    hb_sp_count: 0,
                    hb_gn_count: 2,
                    hb_intn_count: 0,
                    dent_gn_count: 0,
                    dent_resdnt_count: 0,
                    dent_sp_count: 0,
                    medc_resdnt_count: 0,
                    medc_gn_count: 0,
                    medc_intn_count: 0,
                    medc_sp_count: 2,
                    facility_id: 3919,
                    created_at: null,
                    updated_at: null,
                },
                advertisement: null,
            },
            {
                id: 3920,
                kind: '요양병원',
                name: '감꽃요양병원',
                address: '경상북도 청도군 각북면 헐티로 1229, (각북면)',
                url: '',
                telno: '054-371-7770',
                description: null,
                approval_status: null,
                sido_name: '경북',
                sggu_name: '청도군',
                dong_name: '각북면',
                postno: '38300',
                established_date: 20150827,
                longitude: '128.5663118',
                latitude: '35.7143845',
                care_code:
                    'JDQ4MTYyMiM4MSMkMSMkMCMkOTkkNTgxMzUxIzIxIyQxIyQ1IyQ4OSQyNjEyMjIjNDEjJDEjJDQjJDgz',
                facility_number: null,
                created_at: '2025-09-16T04:13:46.922Z',
                updated_at: '2025-09-16T04:13:46.922Z',
                facility_status: {
                    id: 1355,
                    total_patients_count: 0,
                    man_patients_count: 0,
                    woman_patients_count: 0,
                    user_capacity: 0,
                    doctor_count: 3,
                    manager_count: 0,
                    hb_doctor_count: 0,
                    dent_doctor_count: 0,
                    medc_doctor_count: 0,
                    hb_resdnt_count: 0,
                    hb_sp_count: 1,
                    hb_gn_count: 0,
                    hb_intn_count: 0,
                    dent_gn_count: 0,
                    dent_resdnt_count: 0,
                    dent_sp_count: 0,
                    medc_resdnt_count: 0,
                    medc_gn_count: 0,
                    medc_intn_count: 0,
                    medc_sp_count: 2,
                    facility_id: 3920,
                    created_at: null,
                    updated_at: null,
                },
                advertisement: null,
            },
            {
                id: 3921,
                kind: '요양병원',
                name: '감인의료재단 신갈백세요양병원',
                address:
                    '경기도 용인시 기흥구 신정로159번길 60, 신갈백세암요양병원 (신갈동)',
                url: '',
                telno: '031-693-6900',
                description: null,
                approval_status: null,
                sido_name: '경기',
                sggu_name: '용인기흥구',
                dong_name: '신갈동',
                postno: '16945',
                established_date: 20130709,
                longitude: '127.0971813',
                latitude: '37.2868405',
                care_code:
                    'JDQ4MTYyMiM1MSMkMSMkMCMkOTkkNTgxMzUxIzMxIyQxIyQzIyQ3MiQzNjE0ODEjNjEjJDEjJDgjJDgz',
                facility_number: null,
                created_at: '2025-09-16T04:13:51.508Z',
                updated_at: '2025-09-16T04:13:51.508Z',
                facility_status: {
                    id: 1356,
                    total_patients_count: 0,
                    man_patients_count: 0,
                    woman_patients_count: 0,
                    user_capacity: 0,
                    doctor_count: 0,
                    manager_count: 0,
                    hb_doctor_count: 0,
                    dent_doctor_count: 0,
                    medc_doctor_count: 0,
                    hb_resdnt_count: 0,
                    hb_sp_count: 0,
                    hb_gn_count: 0,
                    hb_intn_count: 0,
                    dent_gn_count: 0,
                    dent_resdnt_count: 0,
                    dent_sp_count: 0,
                    medc_resdnt_count: 0,
                    medc_gn_count: 0,
                    medc_intn_count: 0,
                    medc_sp_count: 0,
                    facility_id: 3921,
                    created_at: null,
                    updated_at: null,
                },
                advertisement: null,
            },
        ],
    };

    return res;
};

const getFacilityById = () => {
    return {
        id: 3919,
        kind: '요양병원',
        name: '가평푸른숲요양병원',
        address: '경기도 가평군 상면 물골길 262-23, (상면)',
        url: '',
        telno: '1661-9099',
        description: null,
        approval_status: null,
        sido_name: '경기',
        sggu_name: '가평군',
        dong_name: '상면',
        postno: '12440',
        established_date: 20170901,
        longitude: 127.3042465,
        latitude: 37.8409105,
        care_code:
            'JDQ4MTYyMiM1MSMkMSMkMCMkOTkkNTgxMzUxIzQxIyQxIyQ3IyQ5MiQyNjEyMjIjNzEjJDEjJDgjJDgz',
        facility_number: null,
        average_rating: 0,
        review_count: 0,
        created_at: '2025-09-16T04:13:46.911Z',
        updated_at: '2025-09-16T04:13:46.911Z',
        facility_status: {
            id: 1354,
            total_patients_count: 0,
            man_patients_count: 0,
            woman_patients_count: 0,
            user_capacity: 0,
            doctor_count: 4,
            manager_count: 0,
            hb_doctor_count: 0,
            dent_doctor_count: 0,
            medc_doctor_count: 0,
            hb_resdnt_count: 0,
            hb_sp_count: 0,
            hb_gn_count: 2,
            hb_intn_count: 0,
            dent_gn_count: 0,
            dent_resdnt_count: 0,
            dent_sp_count: 0,
            medc_resdnt_count: 0,
            medc_gn_count: 0,
            medc_intn_count: 0,
            medc_sp_count: 2,
            facility_id: 3919,
            created_at: null,
            updated_at: null,
        },
        advertisements: [],
    };
};

const getCommunities = () => {
    return {
        Message: 'Success',
        ResultCode: 'OK',
        Community: [
            {
                id: 17,
                title: '5 - 수정',
                createdAt: '2025-10-06T18:17:39.204Z',
                content: '5',
                images: [
                    'https://capstone-care-bucket.s3.ap-northeast-2.amazonaws.com/image/community/1-1759774658879.jpg',
                    'https://capstone-care-bucket.s3.ap-northeast-2.amazonaws.com/image/community/1-1759774658924.jpg',
                ],
                totalComments: '0',
                user: {
                    id: 1,
                    name: '문소정',
                },
            },
            {
                id: 16,
                title: '사다수',
                createdAt: '2025-10-06T18:16:36.555Z',
                content: '사다수',
                images: [],
                totalComments: '0',
                user: {
                    id: 1,
                    name: '문소정',
                },
            },
        ],
    };
};

const getReviews = ()=>{

}

const mockApi = {
    getFacilities,
    getFacilityById,
    getCommunities,
    getReviews,
};

export default mockApi;
